import os
import secrets
import logging

logger = logging.getLogger(__name__)


def _load_env_local():
    """Parse a simple `.env-local` file in the project root and inject any
    key=value pairs into os.environ *only if the env var is not already set*.

    This makes SECRET_KEY survivable across Python restarts without forcing
    operators to manually export the value. Values set via the real process
    environment always take priority.
    """
    local_env_path = os.path.join(os.path.dirname(__file__), '.env-local')
    if not os.path.isfile(local_env_path):
        return
    try:
        with open(local_env_path, 'r', encoding='utf-8') as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, value = line.partition('=')
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and key not in os.environ and value:
                    os.environ[key] = value
    except OSError as exc:
        logger.warning("Failed to read %s: %s", local_env_path, exc)


def _generate_secret_key():
    """Generate a cryptographically secure 64-char (32-byte) hex SECRET_KEY
    and persist it to a .env-local file so it survives reloads while never
    being hardcoded into source or checked into version control.
    """
    new_key = secrets.token_hex(32)
    local_env_path = os.path.join(os.path.dirname(__file__), '.env-local')
    try:
        with open(local_env_path, 'a', encoding='utf-8') as f:
            f.write(f"\n# Auto-generated by config.py on {__name__} load\nSECRET_KEY={new_key}\n")
        logger.warning(
            "SECRET_KEY was not provided via environment variable. A new "
            "cryptographically secure key was generated and saved to %s. "
            "Set the SECRET_KEY environment variable explicitly for production "
            "deployments and restart the app.",
            local_env_path
        )
    except OSError as exc:
        logger.error(
            "SECRET_KEY env var missing, and failed to write generated key to "
            "%s (%s). Using an in-memory random key — sessions and signed CSRF "
            "tokens will be invalidated on every restart.",
            local_env_path,
            exc,
        )
    return new_key


_load_env_local()


class Config:
    # SECRET_KEY MUST be provided via environment variable in production.
    # As a last resort (dev only) we generate a unique cryptographically secure
    # key at first load and persist it to .env-local; we NEVER fall back to a
    # hardcoded, publicly known string like the previous
    # 'dev-secret-key-change-in-production' default.
    SECRET_KEY = os.environ.get('SECRET_KEY') or _generate_secret_key()

    DATABASE_PATH = os.path.join(os.path.dirname(__file__), 'database', 'history.db')
